# Render.com deployment configuration for GuessGame
# This file tells Render how to build and run your Flask application

services:
  - type: web
    name: guessgame
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    plan: free
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
    # Environment variables (you'll need to set these in Render dashboard):
    # - AZURE_OPENAI_ENDPOINT
    # - AZURE_OPENAI_API_KEY  
    # - AZURE_OPENAI_DEPLOYMENT_NAME
    # - DATABASE_URL (if using external PostgreSQL like Supabase)
    # - SECRET_KEY
